### ISSUE TITLE
Download a model from its URN

### ISSUE THREAD

**Issue by paulgovan** [Developer-Autodesk/library-javascript-view.and.data.api#2]
Would it be possible to update this example to allow for downloading a model based on its URN?

As shown in this example, [https://github.com/Developer-Autodesk/view-and-data-npm](https://github.com/Developer-Autodesk/view-and-data-npm)

**Comment by leefsmp** [comment]
Already done and this is rather a feature you would use on the server side, so I created an npm package for it: [https://github.com/Developer-Autodesk/view-and-data-npm](https://github.com/Developer-Autodesk/view-and-data-npm)

**Comment by paulgovan** [comment]
Excellent! Though I am very inexperienced in nodejs. Do you know how I might be able to convert this module to an ordinary javascript library such as shown here, [https://github.com/Developer-Autodesk/library-javascript-view.and.data.api](https://github.com/Developer-Autodesk/library-javascript-view.and.data.api)

**Comment by leefsmp** [comment]
I would recommend you do the download operation on the server side, you won't be able to save files to your disk recreating the required folder structure due to browser restrictions working with the file system. It would be probably easier for your to learn how to use a simple node.js script that downloads the viewables than converting this npm to work in the browser.

**Comment by paulgovan** [comment]
Great! Thanks again for your help.
